language: generic 

sudo: required
# For root user it's required 

services:
  - docker 
  # Before start install docker in the new container 

before_install:
  - docker build -t sasi/docker-react -f Dockerfile.dev . 


script:
  - docker run -e CI=true sasi/docker-react npm run test
  # when new commits, travis takes the changes and build the docker image and run the script 
  # Here it will run test case and return the coverage, that's why addedd -- --coverage 

