services: 
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes: 
       - /app/node_modules
       - .:/app
    ports: 
       - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  tests: 
    build: 
      context: . 
      dockerfile: Dockerfile.dev 
    volumes: 
      - /app/node_modules
      - ./app
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "run", test]
        
    
   

